---
- name: Copy the Nginx VTS Exporter systemd service file
  template:
    src: nginx_vts_exporter.service.j2
    dest: /etc/systemd/system/nginx_vts_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart nginx_vts_exporter
