---
- name: Create the exporter group
  group:
    name: "{{ nginx_vts_exporter_system_group }}"
    state: present
    system: true
  when: nginx_vts_exporter_system_group != "root"

- name: Create the exporter user
  user:
    name: "{{ nginx_vts_exporter_system_user }}"
    groups: "{{ nginx_vts_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: nginx_vts_exporter_system_user != "root"

- name: Download exporter binary to local folder
  become: false
  get_url:
    url: "{{ nginx_vts_exporter_download_url }}/v{{ nginx_vts_exporter_version }}/{{ nginx_vts_exporter_download_basename }}.tar.gz"
    dest: "/tmp/{{ nginx_vts_exporter_download_basename }}.tar.gz"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  # delegate_to: localhost
  check_mode: false

- name: Unpack exporter binary
  become: false
  unarchive:
    src: "/tmp/{{ nginx_vts_exporter_download_basename }}.tar.gz"
    remote_src: yes
    dest: "/tmp"
    creates: "/tmp/{{ nginx_vts_exporter_download_basename }}/nginx-vts-exporter"
  # delegate_to: localhost
  check_mode: false

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Propagate exporter binaries
  copy:
    src: "/tmp/{{ nginx_vts_exporter_download_basename }}/nginx-vts-exporter"
    remote_src: yes
    dest: "/usr/local/bin/nginx-vts-exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart nginx_vts_exporter
  when: not ansible_check_mode
